# Generated by Django 4.0.4 on 2022-04-23 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ml_forum', '0002_posts_sections_topics_userprofiles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='message',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='time_update',
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
