# Generated by Django 4.0.4 on 2022-04-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_forum', '0005_alter_userprofiles_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='start_post_id',
        ),
        migrations.AddField(
            model_name='topics',
            name='start_post',
            field=models.TextField(blank=True),
        ),
    ]
