# Generated by Django 4.0.4 on 2022-04-24 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ml_forum', '0007_remove_topics_start_post_posts_start_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='topic_id',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='topics',
            old_name='section_id',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='topics',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
