# Generated by Django 4.0.4 on 2022-04-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_forum', '0009_rename_posts_post_rename_sections_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='photos/default.jpg', upload_to='photos/'),
        ),
    ]
