# Generated by Django 4.0.4 on 2022-04-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_forum', '0011_post_reply_to_post_reply_watched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verify_code',
            field=models.IntegerField(default=None),
        ),
    ]
