# Generated by Django 4.0.4 on 2022-04-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_forum', '0013_alter_userprofile_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='verify_code',
            field=models.IntegerField(blank=True),
        ),
    ]
