# Generated by Django 4.0.4 on 2022-04-26 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ml_forum', '0014_alter_userprofile_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='biography',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, max_length=25, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='github',
            field=models.CharField(blank=True, max_length=25, verbose_name='Гитхаб'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Публичный профиль'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=25, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='photos/default.jpg', upload_to='photos/', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='surname',
            field=models.CharField(blank=True, max_length=25, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram',
            field=models.CharField(blank=True, max_length=25, verbose_name='Телеграм'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='verify_code',
            field=models.IntegerField(default=-1),
        ),
    ]
